"""Streamlit dashboard for the independent Tier-2 accuracy recheck.

Run with:  streamlit run dashboard/app.py

This dashboard never imports anything from the original ForecastPH repo.
It only reads whatever is in `data/evaluations/` (bridge-exported or
synthetic sample JSON) and recomputes everything itself via `recheck/`.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from recheck.aggregate import (
    MODEL_LABELS,
    best_model_counts,
    comparisons_to_dataframe,
    mismatch_table,
    sector_breakdown,
    win_rate_summary,
)
from recheck.compare import DEFAULT_TOLERANCE, compare_all
from recheck.denominator import RawDataError, recompute_mase_denominator
from recheck.loader import load_all_exports
from recheck.schema import PRINCIPAL_MODELS

st.set_page_config(
    page_title="PSE Model Accuracy Recheck (Tier 2)",
    page_icon="\U0001F4C8",
    layout="wide",
)

# ---------------------------------------------------------------------------
# Sidebar - data source and settings
# ---------------------------------------------------------------------------

st.sidebar.title("Data source")
data_dir_input = st.sidebar.text_input("Evaluation export directory", value="data/evaluations")
tolerance = st.sidebar.number_input(
    "Reported-vs-recomputed tolerance",
    min_value=0.0,
    value=DEFAULT_TOLERANCE,
    format="%.8f",
    help="Max allowed absolute difference between this repo's recomputed metric "
    "and the value the original pipeline reported, before it's flagged as a mismatch.",
)
raw_dir_input = st.sidebar.text_input(
    "Raw OHLCV directory (optional, for MASE-denominator cross-check)",
    value="",
    help="Point at a local copy of the original repo's backend/data/raw/ folder "
    "to independently recompute the MASE denominator from scratch. Leave blank to skip.",
)

st.sidebar.markdown("---")
st.sidebar.caption(
    "No real data yet? Run:\n\n"
    "`python scripts/generate_sample_data.py`\n\n"
    "to populate `data/evaluations/` with clearly-labeled synthetic demo data."
)

data_dir = Path(data_dir_input)
if not data_dir.is_dir():
    st.error(
        f"Directory `{data_dir}` not found. Point the sidebar at a directory of "
        f"bridge-exported `<SYMBOL>.json` files, or generate sample data first "
        f"(see sidebar)."
    )
    st.stop()

result = load_all_exports(data_dir)

if result.load_errors:
    with st.sidebar.expander(f"\u26a0\ufe0f {len(result.load_errors)} file(s) failed to load", expanded=False):
        for symbol, error in result.load_errors.items():
            st.write(f"**{symbol}**: {error}")

if not result.exports:
    st.warning("No valid company exports were found in this directory.")
    st.stop()

is_synthetic = bool(result.manifest and "SYNTHETIC" in str(result.manifest.get("note", "")))
if is_synthetic:
    st.info(
        "\U0001F9EA This is **synthetic demo data** generated by "
        "`scripts/generate_sample_data.py` - not real ForecastPH results. "
        "One company's metrics were deliberately corrupted to show what the "
        "mismatch view below looks like when it finds something.",
        icon="\U0001F9EA",
    )

comparisons = compare_all(result.exports, tolerance=tolerance)
df = comparisons_to_dataframe(comparisons, result.exports)

validation_error_rows = []
validation_warning_rows = []
for symbol, export in result.exports.items():
    for issue in export.issues:
        row = {"symbol": symbol, "severity": issue.severity, "message": issue.message}
        (validation_error_rows if issue.severity == "error" else validation_warning_rows).append(row)

st.title("PSE Model Accuracy Recheck")
st.caption(
    "Independent recomputation of RMSE / MAE / MASE / R\u00b2 for Lag-Informed Regression, "
    "ARIMA, and LSTM against the Naive benchmark, over the full Fresh Model Training "
    "evaluation window - not the original pipeline's own reported numbers."
)

n_companies = len(result.exports)
n_mismatches = len(mismatch_table(df))
n_validation_errors = len(validation_error_rows)

status_cols = st.columns(4)
status_cols[0].metric("Companies loaded", n_companies)
status_cols[1].metric(
    "Evaluation window",
    f"{df['evaluation_start'].min()} \u2192 {df['evaluation_end'].max()}",
)
status_cols[2].metric(
    "Reported/recomputed mismatches",
    n_mismatches,
    delta=None if n_mismatches == 0 else f"{n_mismatches} flagged",
    delta_color="inverse",
)
status_cols[3].metric(
    "Validation errors",
    n_validation_errors,
    delta=None if n_validation_errors == 0 else f"{n_validation_errors} companies",
    delta_color="inverse",
)

tab_overview, tab_company, tab_mismatches, tab_integrity, tab_denominator = st.tabs(
    ["Overview", "Per-company detail", "Recomputed vs. Reported", "Data integrity", "MASE denominator check"]
)

# ---------------------------------------------------------------------------
# Overview
# ---------------------------------------------------------------------------
with tab_overview:
    st.subheader("Win rate vs. Naive (recomputed)")
    st.caption("Share of companies where a model's recomputed MASE < 1.0, i.e. it beat the Naive benchmark.")
    win_df = win_rate_summary(df)
    left, right = st.columns([1, 1])
    with left:
        st.dataframe(
            win_df[["model_label", "companies_beating_naive", "total_companies", "win_rate_pct", "median_mase", "median_rmse"]]
            .rename(columns={
                "model_label": "Model", "companies_beating_naive": "Beats Naive",
                "total_companies": "Total companies", "win_rate_pct": "Win rate %",
                "median_mase": "Median MASE", "median_rmse": "Median RMSE",
            }),
            hide_index=True,
            use_container_width=True,
        )
    with right:
        fig = px.bar(win_df, x="model_label", y="win_rate_pct", text="win_rate_pct",
                     labels={"model_label": "Model", "win_rate_pct": "Win rate % (MASE < 1.0)"},
                     color="model_label", color_discrete_sequence=px.colors.qualitative.Set2)
        fig.add_hline(y=50, line_dash="dot", annotation_text="50%", annotation_position="top left")
        fig.update_traces(texttemplate="%{text:.1f}%", textposition="outside")
        fig.update_layout(showlegend=False, yaxis_range=[0, 105])
        st.plotly_chart(fig, use_container_width=True)

    st.subheader("Best model by company (lowest recomputed RMSE)")
    counts_df = best_model_counts(df)
    left, right = st.columns([1, 1])
    with left:
        st.dataframe(
            counts_df.rename(columns={"model_label": "Model", "companies_best": "Companies where it's best"}),
            hide_index=True, use_container_width=True,
        )
    with right:
        fig = px.pie(counts_df, names="model_label", values="companies_best", hole=0.45,
                     color_discrete_sequence=px.colors.qualitative.Set2)
        st.plotly_chart(fig, use_container_width=True)

    st.subheader("Recomputed MASE distribution by model")
    principal_df = df[df["is_principal"]]
    fig = px.box(principal_df, x="model_label", y="recomputed_mase", points="all",
                 color="model_label", color_discrete_sequence=px.colors.qualitative.Set2,
                 labels={"model_label": "Model", "recomputed_mase": "Recomputed MASE"},
                 hover_data=["symbol"])
    fig.add_hline(y=1.0, line_dash="dash", line_color="red",
                  annotation_text="MASE = 1.0 (Naive)", annotation_position="top right")
    fig.update_layout(showlegend=False)
    st.plotly_chart(fig, use_container_width=True)

    breakdown = sector_breakdown(df)
    if not breakdown.empty:
        st.subheader("Median MASE by sector")
        fig = px.bar(breakdown, x="sector", y="median_mase", color="model_label", barmode="group",
                     color_discrete_sequence=px.colors.qualitative.Set2,
                     labels={"sector": "Sector", "median_mase": "Median recomputed MASE", "model_label": "Model"})
        fig.add_hline(y=1.0, line_dash="dash", line_color="red")
        st.plotly_chart(fig, use_container_width=True)

# ---------------------------------------------------------------------------
# Per-company detail
# ---------------------------------------------------------------------------
with tab_company:
    symbols = sorted(result.exports)
    selected_symbol = st.selectbox("Company", symbols)
    export = result.exports[selected_symbol]
    company_df = df[df["symbol"] == selected_symbol].copy()

    header_cols = st.columns(4)
    header_cols[0].markdown(f"**{export.name or selected_symbol}**")
    header_cols[1].markdown(f"Sector: **{export.sector or 'n/a'}**")
    header_cols[2].markdown(f"Evaluation window: **{export.evaluation_start} \u2192 {export.evaluation_end}**")
    header_cols[3].markdown(f"Evaluation dates: **{len(export.target_dates)}**")

    if export.has_errors:
        st.error("This company's export has validation errors - metrics below may not be trustworthy.")
        for issue in export.issues:
            if issue.severity == "error":
                st.write(f"- {issue.message}")

    st.subheader("Reported vs. recomputed metrics")
    display_df = company_df[
        ["model_label", "reported_rmse", "recomputed_rmse", "reported_mae", "recomputed_mae",
         "reported_mase", "recomputed_mase", "reported_r2", "recomputed_r2", "within_tolerance"]
    ].rename(columns={
        "model_label": "Model", "reported_rmse": "RMSE (reported)", "recomputed_rmse": "RMSE (recomputed)",
        "reported_mae": "MAE (reported)", "recomputed_mae": "MAE (recomputed)",
        "reported_mase": "MASE (reported)", "recomputed_mase": "MASE (recomputed)",
        "reported_r2": "R\u00b2 (reported)", "recomputed_r2": "R\u00b2 (recomputed)",
        "within_tolerance": "Matches",
    })
    st.dataframe(display_df, hide_index=True, use_container_width=True)

    st.subheader("Predicted vs. actual Close - full evaluation window")
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=export.target_dates, y=export.actual_closes, name="Actual",
        mode="lines", line=dict(color="black", width=2),
    ))
    colors = {"lag_reg": "#1f77b4", "arima": "#ff7f0e", "lstm": "#2ca02c", "naive": "#7f7f7f"}
    for model in ("lag_reg", "arima", "lstm", "naive"):
        fig.add_trace(go.Scatter(
            x=export.target_dates, y=export.predicted_closes_by_model[model],
            name=MODEL_LABELS[model], mode="lines",
            line=dict(color=colors[model], width=1, dash="dot" if model == "naive" else "solid"),
            opacity=0.85,
        ))
    fig.update_layout(
        xaxis_title="Target date", yaxis_title="Close",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        height=480,
    )
    st.plotly_chart(fig, use_container_width=True)

    with st.expander("Show underlying per-date table"):
        detail_rows = pd.DataFrame({
            "target_date": export.target_dates,
            "actual_close": export.actual_closes,
            **{f"{model}_predicted": export.predicted_closes_by_model[model]
               for model in ("lag_reg", "arima", "lstm", "naive")},
        })
        st.dataframe(detail_rows, hide_index=True, use_container_width=True)

# ---------------------------------------------------------------------------
# Recomputed vs. Reported (mismatches)
# ---------------------------------------------------------------------------
with tab_mismatches:
    st.subheader("Every model/company where recomputed metrics disagree with reported metrics")
    st.caption(f"Tolerance: {tolerance}")
    mismatches = mismatch_table(df)
    if mismatches.empty:
        st.success("No mismatches - every reported metric matches this repo's independent recomputation within tolerance.")
    else:
        st.error(f"{len(mismatches)} mismatch(es) found.")
        st.dataframe(
            mismatches[["symbol", "model_label", "reported_rmse", "recomputed_rmse",
                        "reported_mae", "recomputed_mae", "reported_mase", "recomputed_mase",
                        "reported_r2", "recomputed_r2", "max_abs_diff"]],
            hide_index=True, use_container_width=True,
        )

    st.subheader("Full comparison table (all companies, all models)")
    st.dataframe(df.drop(columns=["is_principal"]), hide_index=True, use_container_width=True)
    st.download_button(
        "Download full comparison as CSV",
        data=df.to_csv(index=False).encode("utf-8"),
        file_name="recheck_comparison.csv",
        mime="text/csv",
    )

# ---------------------------------------------------------------------------
# Data integrity
# ---------------------------------------------------------------------------
with tab_integrity:
    st.subheader("Validation issues found while independently parsing each export")
    st.caption(
        "Chronological ordering, duplicate dates, matching array lengths, and "
        "actual_close agreement across models are all re-checked here from scratch - "
        "not assumed from the export."
    )
    if not validation_error_rows and not validation_warning_rows:
        st.success("No validation issues found across any loaded company.")
    else:
        if validation_error_rows:
            st.error(f"{len(validation_error_rows)} error(s)")
            st.dataframe(pd.DataFrame(validation_error_rows), hide_index=True, use_container_width=True)
        if validation_warning_rows:
            st.warning(f"{len(validation_warning_rows)} warning(s)")
            st.dataframe(pd.DataFrame(validation_warning_rows), hide_index=True, use_container_width=True)

    if result.manifest:
        st.subheader("Export manifest")
        st.json(result.manifest)

# ---------------------------------------------------------------------------
# MASE denominator cross-check (optional, needs raw OHLCV)
# ---------------------------------------------------------------------------
with tab_denominator:
    st.subheader("Recompute the MASE denominator from raw OHLCV")
    st.caption(
        "Every model's MASE depends on one shared denominator "
        "(mean(|day-over-day Close change|) over the development partition). "
        "This recomputes it directly from raw prices, independent of the export."
    )
    if not raw_dir_input:
        st.info(
            "Enter a raw OHLCV directory in the sidebar to run this check "
            "(e.g. a local copy of the original repo's `backend/data/raw/`, "
            "which is git-committed there and doesn't need the bridge step)."
        )
    else:
        raw_dir = Path(raw_dir_input)
        if not raw_dir.is_dir():
            st.error(f"Directory `{raw_dir}` not found.")
        else:
            rows = []
            for symbol, export in sorted(result.exports.items()):
                csv_path = raw_dir / f"{symbol}.csv"
                if not csv_path.is_file():
                    rows.append({"symbol": symbol, "status": "raw CSV not found", "recomputed": None,
                                 "reported": export.mase_denominator, "relative_diff_pct": None})
                    continue
                try:
                    check = recompute_mase_denominator(
                        symbol, csv_path,
                        evaluation_start=export.evaluation_start,
                        reported_denominator=export.mase_denominator,
                    )
                    rows.append({
                        "symbol": symbol, "status": "OK" if check.within_tolerance else "MISMATCH",
                        "recomputed": check.recomputed_denominator, "reported": check.reported_denominator,
                        "relative_diff_pct": round(check.relative_diff_pct, 3),
                    })
                except RawDataError as exc:
                    rows.append({"symbol": symbol, "status": f"error: {exc}", "recomputed": None,
                                 "reported": export.mase_denominator, "relative_diff_pct": None})
            denom_df = pd.DataFrame(rows)
            n_mismatch = (denom_df["status"] == "MISMATCH").sum()
            if n_mismatch:
                st.error(f"{n_mismatch} compan(y/ies) have a MASE denominator that disagrees with the raw-CSV recomputation.")
            else:
                st.success("All recomputed denominators match reported values within tolerance (or raw data was unavailable).")
            st.dataframe(denom_df, hide_index=True, use_container_width=True)
